---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Library loading
```{r,echo=TRUE}
library(dplyr)
library(ggplot2)
```


## Loading and preprocessing the data
```{r,echo=TRUE}
#Load,process and transform the data.

data <- read.csv("activity.csv")%>%
          tbl_df()
```


## What is mean total number of steps taken per day?
```{r,echo=TRUE}
#Calculate the total number of steps taken per day.

grp_data <- group_by(data,date)%>%
          summarize(steps = sum(steps))

#Make a histogram of the total number of steps taken each day.

hist(grp_data$steps, xlab = "Total daily Steps",main="Histogram of mean total number of steps taken per day", breaks = 40)

# Calculate and report the mean and median of the total number of steps taken per day.

mean <- mean(grp_data$steps, na.rm = TRUE)
median <- median(grp_data$steps, na.rm = TRUE)
cbind(mean,median)
```


## What is the average daily activity pattern?
```{r, echo=TRUE}
# Make a time series plot (i.e. type = "l") of the 5-minute interval (x-axis) and the average number of steps taken, averaged across all days (y-axis).

five_avg <- group_by(data, interval) %>%
          summarise(steps = mean(steps, na.rm = TRUE))
ggplot(five_avg, aes(interval, steps)) + geom_line()

#Which 5-minute interval, on average across all the days in the dataset, contains the maximum number of steps?

five_avg[five_avg$steps==max(five_avg$steps),]

```


## Imputing missing values
```{r, echo=TRUE}
# Calculate and report the total number of missing values in the dataset (i.e. the total number of rows with NA).

na <- data[(is.na(data)),]
nrow(na)

# Devise a strategy for filling in all of the missing values in the dataset. The strategy does not need to be sophisticated. For example, you could use the mean/median for that day, or the mean for that 5-minute interval, etc.

place_mean <- function(x) replace(x, is.na(x), mean(x, na.rm = TRUE))

# Create a new dataset that is equal to the original dataset but with the missing data filled in.

replace_na <- group_by(data, interval)%>%
          mutate(steps= place_mean(steps))
head(replace_na)

#Make a histogram of the total number of steps taken each day and Calculate and report the mean and median total number of steps taken per day. 

replace_grp <- group_by(replace_na,date) %>%
          summarise(steps = sum(steps))

hist(replace_grp$steps, xlab = "Total daily Steps",main="Histogram after data imputation", breaks = 40)

mean_imput <- mean(replace_grp$steps)
median_imput <- median(replace_grp$steps)
cbind(mean,median)

#Do these values differ from the estimates from the first part of the assignment? 
# Relative frequencies remains same, but the absolute frequencies changed.

#What is the impact of imputing missing data on the estimates of the total daily number of steps?
# Same result as imputed with the mean value.

```


## Are there differences in activity patterns between weekdays and weekends?
```{r, echo=TRUE}

# Create a new factor variable in the dataset with two levels – “weekday” and “weekend” indicating whether a given date is a weekday or weekend day.

replace_na$dayofweek <- weekdays(as.Date(replace_na$date))
replace_na$weekend <-as.factor(replace_na$dayofweek=="Saturday"|replace_na$dayofweek=="Sunday")
levels(replace_na$weekend) <- c("Weekday", "Weekend")

# Make a panel plot containing a time series plot (i.e. type = "l") of the 5-minute interval (x-axis) and the average number of steps taken, averaged across all weekday days or weekend days (y-axis). See the README file in the GitHub repository to see an example of what this plot should look like using simulated data.

act_weekday <- replace_na[replace_na$weekend=="Weekday",]
act_weekend <- replace_na[replace_na$weekend=="Weekend",]

act.int.weekday <- group_by(act_weekday, interval)
act.int.weekday <- summarize(act.int.weekday, steps=mean(steps))
act.int.weekday$weekend <- "Weekday"
act.int.weekend <- group_by(act_weekend, interval)
act.int.weekend <- summarize(act.int.weekend, steps=mean(steps))
act.int.weekend$weekend <- "Weekend"

act.int <- rbind(act.int.weekday, act.int.weekend)
act.int$weekend <- as.factor(act.int$weekend)
ggplot(act.int, aes(interval, steps)) + geom_line() + facet_grid(weekend ~ .)

```

